//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.04 at 03:23:22 PM EET 
//


package com.mcnz.jee.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentURLsInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentURLsInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ContentBodiesList" type="{http://soap.jee.mcnz.com/}ContentBodiesList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentURLsInfo", propOrder = {
    "contentBodiesList"
})
public class ContentURLsInfo {

    @XmlElement(name = "ContentBodiesList", required = true)
    protected ContentBodiesList contentBodiesList;

    /**
     * Gets the value of the contentBodiesList property.
     * 
     * @return
     *     possible object is
     *     {@link ContentBodiesList }
     *     
     */
    public ContentBodiesList getContentBodiesList() {
        return contentBodiesList;
    }

    /**
     * Sets the value of the contentBodiesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentBodiesList }
     *     
     */
    public void setContentBodiesList(ContentBodiesList value) {
        this.contentBodiesList = value;
    }

}
