//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.07 at 12:01:20 AM EET 
//


package com.mcnz.jee.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mcnz.jee.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mcnz.jee.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IdentitiesList }
     * 
     */
    public IdentitiesList createIdentitiesList() {
        return new IdentitiesList();
    }

    /**
     * Create an instance of {@link ContentIdentity }
     * 
     */
    public ContentIdentity createContentIdentity() {
        return new ContentIdentity();
    }

    /**
     * Create an instance of {@link ContentURLsList }
     * 
     */
    public ContentURLsList createContentURLsList() {
        return new ContentURLsList();
    }

    /**
     * Create an instance of {@link ContentURLsInfo }
     * 
     */
    public ContentURLsInfo createContentURLsInfo() {
        return new ContentURLsInfo();
    }

    /**
     * Create an instance of {@link ContentBodiesList }
     * 
     */
    public ContentBodiesList createContentBodiesList() {
        return new ContentBodiesList();
    }

    /**
     * Create an instance of {@link ContentBodyInfo }
     * 
     */
    public ContentBodyInfo createContentBodyInfo() {
        return new ContentBodyInfo();
    }

}
